import { motion } from 'framer-motion';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft, FileText } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service - Edzio\'s Portfolio',
  description: 'Terms and conditions for using Edzio\'s portfolio website and services.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen py-20 px-6">
      <div className="container mx-auto max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <Link href="/">
            <Button variant="ghost" className="mb-6">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Portfolio
            </Button>
          </Link>

          <div className="text-center mb-12">
            <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center">
              <FileText className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-4xl md:text-6xl font-bold mb-4 bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
              Terms of Service
            </h1>
            <p className="text-xl text-muted-foreground">
              Last updated: January 2024
            </p>
          </div>

          <Card>
            <CardContent className="p-8 prose prose-invert max-w-none">
              <h2>1. Acceptance of Terms</h2>
              <p>
                By accessing and using Edzio&apos;s Portfolio website, you accept and agree to be bound by the terms and provision of this agreement.
              </p>

              <h2>2. Use License</h2>
              <p>
                Permission is granted to temporarily download one copy of the materials on Edzio&apos;s Portfolio for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
              </p>
              <ul>
                <li>modify or copy the materials</li>
                <li>use the materials for any commercial purpose or for any public display (commercial or non-commercial)</li>
                <li>attempt to decompile or reverse engineer any software contained on the website</li>
                <li>remove any copyright or other proprietary notations from the materials</li>
              </ul>

              <h2>3. Disclaimer</h2>
              <p>
                The materials on Edzio&apos;s Portfolio are provided on an &apos;as is&apos; basis. Edzio makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
              </p>

              <h2>4. AI Chatbot Usage</h2>
              <p>
                The AI chatbot feature is provided for informational purposes about Edzio&apos;s work and capabilities. While efforts are made to ensure accuracy, responses are generated by AI and should not be considered as formal commitments or guarantees.
              </p>

              <h2>5. Data Collection and Privacy</h2>
              <p>
                We collect and process personal data in accordance with our Privacy Policy. By using this website, you consent to the collection and use of information as outlined in the Privacy Policy.
              </p>

              <h2>6. Service Inquiries and Contracts</h2>
              <p>
                Inquiries submitted through the "Hire Me" form or other contact methods do not constitute a binding agreement. All project work requires a separate, formal contract agreement.
              </p>

              <h2>7. Intellectual Property</h2>
              <p>
                All content, including but not limited to text, graphics, logos, images, and software, is the property of Edzio and is protected by copyright and other intellectual property laws.
              </p>

              <h2>8. Limitations</h2>
              <p>
                In no event shall Edzio or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on this website.
              </p>

              <h2>9. Accuracy of Materials</h2>
              <p>
                The materials appearing on this website could include technical, typographical, or photographic errors. Edzio does not warrant that any of the materials on its website are accurate, complete, or current.
              </p>

              <h2>10. Modifications</h2>
              <p>
                Edzio may revise these terms of service at any time without notice. By using this website, you are agreeing to be bound by the then current version of these terms of service.
              </p>

              <h2>11. Contact Information</h2>
              <p>
                If you have any questions about these Terms of Service, please contact us through the website's contact form or email.
              </p>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}